#!/usr/bin/env bash
# Unattended Phase 1 -> Phase 2 pipeline. Start it once, in its own tmux session:
#
#   tmux new-session -d -s strat_pipeline 'bash scripts/pipeline.sh'
#
# It runs the plan's runs one after another on GPU 0, makes the plots, appends the
# numbers to each phase's docs/outputs/<NN>/output.md, commits, pushes and opens the
# phase PR. Every step is skipped if its output already exists, so it can be
# restarted after an interruption. Progress: runs/pipeline.log
set -uo pipefail
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO"
# shellcheck disable=SC1091
source "$REPO/scripts/env.sh"
LOG="$REPO/runs/pipeline.log"; mkdir -p "$REPO/runs"
ERA5_TAPE=/home/susanne/docs/AIDE-atmosphere_validation/AIDE-atmosphere/output/era5_monthly_tape.nc
ALL_MONTHS=1,2,3,4,5,6,7,8,9,10,11,12

step() { echo "[pipeline] $(date -Is) $*" | tee -a "$LOG"; }
g() { for _ in $(seq 1 60); do if out=$(git "$@" 2>&1); then [ -n "$out" ] && echo "$out"; return 0; fi
        case "$out" in *index.lock*) sleep 1;; *) echo "$out"; return 1;; esac; done; echo "gave up: git $*"; return 1; }

# run_model <name> <hydra overrides...>  -- foreground, GPU 0, skipped if finished
run_model() {
  local name="$1"; shift
  local rundir="$REPO/runs/$name"
  if grep -q '\[launch\].*exit=0' "$rundir/log.txt" 2>/dev/null; then step "skip $name (done)"; return 0; fi
  while tmux ls 2>/dev/null | grep '^strat_' | grep -qv strat_pipeline; do sleep 30; done
  mkdir -p "$rundir"; step "run $name: $*"
  ( cd "$rundir" && python -m jcm.main --config-dir "$REPO/jcm_strat/config" "$@" hydra.run.dir="$rundir" ) >> "$rundir/log.txt" 2>&1
  local rc=$?
  echo "[launch] $(date -Is) exit=$rc" >> "$rundir/log.txt"
  step "done $name exit=$rc"; return $rc
}

wait_for_session() { while tmux has-session -t "$1" 2>/dev/null; do sleep 30; done; }

analyse() {  # analyse <run> <outdir> <label> <title>
  local run="$1" out="$2" label="$3" title="$4"
  mkdir -p "$out"
  { echo; echo "### $run"; echo; echo '```'
    python scripts/throughput.py "runs/$run" --label "$label" --grid T63L95 --csv docs/outputs/throughput.csv | grep -vE 'appended'
    python scripts/run_summary.py "runs/$run" "$out/${run}_summary.png" --last-days 60 | grep -v wrote
    python scripts/plot_zonal_mean.py "runs/$run/longrun_day365.nc" "$out/${run}_zonal_mean.png" \
        --era5-tape "$ERA5_TAPE" --months "$ALL_MONTHS" --title "$title" | grep -v wrote
    echo '```'; echo
    echo "![summary](${run}_summary.png)"; echo "![zonal mean](${run}_zonal_mean.png)"; echo
  } >> "$out/output.md"
  cp "runs/$run/.hydra/config.yaml" "docs/resolved_configs/$run.yaml"
}

open_pr() {  # open_pr <branch> <base> <title> <bodyfile>
  g push -q -u origin "$1" || return 1
  gh pr list --repo reflective-org/jcm-strat --head "$1" --json number -q '.[0].number' | grep -q . && { step "PR for $1 exists"; return 0; }
  gh pr create --repo reflective-org/jcm-strat --base "$2" --head "$1" --title "$3" --body-file "$4" 2>&1 | tail -1 | tee -a "$LOG"
}

############################## Phase 1 ##############################
phase1() {
  g checkout -q phase1-stripped-dry
  wait_for_session strat_p1_dry_1yr                       # the run launched interactively
  if ! grep -q '^## Results' docs/outputs/01_dry/output.md; then
    { echo; echo "## Results (auto-generated by scripts/pipeline.sh)"; echo
      echo "One-year run, dt 12 min, 30-day chunks. Held-Suarez has no seasonal cycle, so the"
      echo "ERA5 comparison row uses the 1989-1994 annual mean of the zonal-mean tape (7-70 hPa)."; } >> docs/outputs/01_dry/output.md
    analyse p1_dry_1yr     docs/outputs/01_dry "P1 dry HS"     "Phase 1: dry Held-Suarez, T63L95, day 365; bottom: minus ERA5 annual mean"
    python scripts/plot_throughput.py docs/outputs/throughput.csv docs/outputs/01_dry/throughput.png
    echo "![throughput](throughput.png)" >> docs/outputs/01_dry/output.md
    sed -i 's/^Status: in progress.*/Status: runs complete, awaiting review (auto-generated results below)./' docs/outputs/01_dry/output.md
    python - <<'PY'
import csv
rows = list(csv.DictReader(open("docs/outputs/throughput.csv")))
with open("PROGRESS.md") as f: s = f.read()
for r in rows:
    if r["label"].startswith("P1") and r["run"] not in s:
        s += f"| 1 | {r['label']} | {r['grid']} | {float(r['dt_min']):g} | {r['days_per_hr']} (e2e {r['e2e_days_per_hr']}) | {r['ms_per_step']} | `{r['run']}` | {r['date']} |\n"
s = s.replace("| 2026-09-02 | 0 — environment, baseline |", "| 2026-09-02 | 1 — stripped dry model | run done (1-yr HS), PR open | [docs/outputs/01_dry/output.md](docs/outputs/01_dry/output.md) |\n| 2026-09-02 | 0 — environment, baseline |")
open("PROGRESS.md", "w").write(s)
PY
  fi
  g add -A docs/outputs/01_dry docs/outputs/throughput.csv docs/resolved_configs PROGRESS.md scripts jcm_strat/config
  g commit -q -m "Phase 1 results: 1-year dry Held-Suarez runs with and without gravity-wave drag on T63L95

Auto-generated by scripts/pipeline.sh: throughput rows, stability summaries
(surface-pressure drift, KE, top-level temperature trend) and zonal-mean
plots against the ERA5 annual mean for both runs." || true
  cat > /tmp/pr1_body.md <<'MD'
## Phase 1 — strip the physics

Dry Held-Suarez on the 95-level high-top grid, one year. The stripped model's throughput is the upper bound on Approach A's speed.

Results, plots and acceptance table: [docs/outputs/01_dry/output.md](docs/outputs/01_dry/output.md).

The planned gravity-wave-drag A/B could not be composed (Held-Suarez is full-field, the drag terms are column-vectorized) and is issue #20; Phases 1-3 run `strat_dry` (Held-Suarez only).

Also in this PR: the Phase 2 experiment config (`experiment/p2_sd.yaml`), the analysis scripts, the unattended pipeline (`scripts/pipeline.sh`), and the branching-model note.
MD
  open_pr phase1-stripped-dry dev "Phase 1: stripped dry Held-Suarez model on T63L95" /tmp/pr1_body.md
}

############################## Phase 2 ##############################
phase2() {
  g checkout -q phase2-specified-dynamics 2>/dev/null || g checkout -q -b phase2-specified-dynamics phase1-stripped-dry
  step "ERA5 prefetch 2005"
  python -m jcm.data.era5 --grid echam_t63_l95_hybrid --start 2004-12-31 --end 2006-01-02 --init >> "$LOG" 2>&1 || { step "ERA5 prefetch failed"; return 1; }
  mkdir -p docs/outputs/02_nudged
  [ -f docs/outputs/02_nudged/output.md ] || cat > docs/outputs/02_nudged/output.md <<'MD'
# Phase 2 — specified dynamics: troposphere nudged to ERA5, stratosphere free

Status: in progress (auto-run by scripts/pipeline.sh).

## Configuration

`+experiment=p2_sd`: Phase-1 dry physics; `init=era5` and `nudging=era5` from WeatherBench2
(6-hourly, 13 levels 50-1000 hPa); winds and temperature nudged with tau = 6 h below
150 hPa (hard cutoff, KEY_DECISIONS #8, issue #1); bottom 2 levels free; start 2005-01-01.

## Runs

| run | days | purpose |
|---|---|---|
| `p2_sd_90d` | 90 | check run |
| `p2_sd_1yr` | 365 | the Phase-2 run (2005) |

## Acceptance (from PLANS.md)

| check | threshold | result |
|---|---|---|
| 365 days stable | 0 NaN vars every chunk | see summary below |
| 500 hPa zonal-mean u RMSE vs ERA5 | < 3 m/s | needs the nudging-check script (issue) |
| zonal-mean T RMSE vs ERA5 below 150 hPa | < 3 K | needs the nudging-check script (issue) |
| no kink at 150 hPa | qualitative | zonal-mean plot |
| Jan-2006 SSW | qualitative | needs daily output (issue) |
| throughput | within 10% of Phase 1 | throughput row |
MD
  run_model p2_sd_90d +experiment=p2_sd run.total_time=90 || return 1
  run_model p2_sd_1yr +experiment=p2_sd run.total_time=365 || return 1
  if ! grep -q '^## Results' docs/outputs/02_nudged/output.md; then
    { echo; echo "## Results (auto-generated by scripts/pipeline.sh)"; echo
      echo "The ERA5 row compares the 2005 model year with the 1989-1994 annual mean of the zonal-mean tape (7-70 hPa)."; } >> docs/outputs/02_nudged/output.md
    analyse p2_sd_1yr docs/outputs/02_nudged "P2 SD" "Phase 2: dry HS + ERA5 nudging below 150 hPa, 2005, day 365; bottom: minus ERA5 annual mean"
    python scripts/plot_throughput.py docs/outputs/throughput.csv docs/outputs/02_nudged/throughput.png
    echo "![throughput](throughput.png)" >> docs/outputs/02_nudged/output.md
    sed -i 's/^Status: in progress.*/Status: runs complete, awaiting review (auto-generated results below)./' docs/outputs/02_nudged/output.md
    python - <<'PY'
import csv
rows = list(csv.DictReader(open("docs/outputs/throughput.csv")))
with open("PROGRESS.md") as f: s = f.read()
for r in rows:
    if r["label"].startswith("P2") and r["run"] not in s:
        s += f"| 2 | {r['label']} | {r['grid']} | {float(r['dt_min']):g} | {r['days_per_hr']} (e2e {r['e2e_days_per_hr']}) | {r['ms_per_step']} | `{r['run']}` | {r['date']} |\n"
s = s.replace("| 2026-09-02 | 1 — stripped dry model |", "| 2026-09-03 | 2 — specified dynamics | runs done (90 d check, 1-yr 2005), PR open | [docs/outputs/02_nudged/output.md](docs/outputs/02_nudged/output.md) |\n| 2026-09-02 | 1 — stripped dry model |")
open("PROGRESS.md", "w").write(s)
PY
  fi
  g add -A docs/outputs/02_nudged docs/outputs/throughput.csv docs/resolved_configs PROGRESS.md
  g commit -q -m "Phase 2 results: ERA5-nudged troposphere below 150 hPa, free stratosphere, 2005

Auto-generated by scripts/pipeline.sh: 90-day check and 1-year run, throughput,
stability summary and zonal-mean plots against the ERA5 annual mean." || true
  cat > /tmp/pr2_body.md <<'MD'
## Phase 2 — specified dynamics

Phase-1 dry model with winds and temperature nudged to WeatherBench2 ERA5 below 150 hPa (tau 6 h), stratosphere free, year 2005. Stacked on the Phase 1 branch; retargets to `dev` when that merges.

Results, plots and acceptance table: [docs/outputs/02_nudged/output.md](docs/outputs/02_nudged/output.md). The quantitative RMSE-vs-ERA5 and SSW checks need the nudging-check script tracked as an issue; the stability, throughput and zonal-mean evidence is in the record.
MD
  open_pr phase2-specified-dynamics phase1-stripped-dry "Phase 2: ERA5-nudged troposphere, free stratosphere (2005)" /tmp/pr2_body.md
}

step "pipeline start on $(hostname), branch $(git branch --show-current)"
phase1 && step "phase 1 complete" || { step "phase 1 FAILED - stopping"; exit 1; }
phase2 && step "phase 2 complete" || { step "phase 2 FAILED - stopping"; exit 1; }
step "pipeline finished"
